# Generated by Django 5.2.1 on 2025-05-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nivel_acceso', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_actual', models.CharField(max_length=255)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('dimensiones', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_kml', models.TextField()),
                ('duracion_estimada_min', models.PositiveIntegerField()),
                ('distancia_km', models.FloatField()),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('paquete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='api.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.cliente')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.conductor')),
                ('estado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.estadoentrega')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.paquete')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('año_de_fabricacion', models.PositiveIntegerField()),
                ('conductor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conductor')),
            ],
        ),
    ]
