# Generated by Django 5.2.1 on 2025-07-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estado_antiguo',
            field=models.CharField(blank=True, help_text='Estado antiguo del paquete', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado_nuevo',
            field=models.CharField(blank=True, help_text='Estado nuevo del paquete', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='rut_destinatario',
            field=models.CharField(help_text='RUT del destinatario (formato: 12.345.678-9)', max_length=12),
        ),
    ]
