# Generated by Django 5.2.1 on 2025-06-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paquete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ubicacion_actual', models.CharField(max_length=255)),
                ('fecha_envio', models.DateField()),
                ('direccion_envio', models.CharField(max_length=255)),
                ('dimensiones', models.FloatField()),
                ('peso', models.FloatField()),
            ],
        ),
    ]
